spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-79-125-124-30.eu-west-1.compute.amazonaws.com:5432/d18fuhegi1bipl?sslmode=require&user=gmvwberyqyfqep&password=f60f0ced1728d912122ee99ea542c87e659428d499709054e110ec9ad9be1a3f
    driverClassName: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jadira:
    usertype:
      autoRegisterUserTypes: true
  boot:
    admin:
      client:
        url: https://veloadmintest.herokuapp.com/

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: https://eurekavelo.herokuapp.com/eureka
    healthcheck:
      enabled: true
